---
name: checks

"on":
  pull_request:
    branches:
      - main

jobs:
  conventional-commits:
    uses: broadinstitute/shared-workflows/.github/workflows/conventional-commit.yaml@v4.0.0
  linting:
    uses: broadinstitute/shared-workflows/.github/workflows/terraform-lint.yaml@v4.0.0
    with:
      tflint_config_path: "../.tflint.hcl"
      working_directory: modules
  static_analysis:
    uses: broadinstitute/shared-workflows/.github/workflows/terraform-static-analyze.yaml@v4.0.0
    secrets:
      wf_github_token: ${{ secrets.github_token }}
    with:
      run_trivy: true
      working_directory: modules
  validation:
    uses: broadinstitute/shared-workflows/.github/workflows/terraform-validate.yaml@v4.0.0
    with:
      terraform_version: "1.12.2"
      working_directory: modules
